WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x037EE1F0>, 'Connect timed out. (connect timeout=5.0)')': /bot695750093:AAHKHhTZ5H3Zi_vUngfTlhHHUhhC2QNSoiI/deleteWebhook
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x037EE1F0>, 'Connect timed out. (connect timeout=5.0)')': /bot695750093:AAHKHhTZ5H3Zi_vUngfTlhHHUhhC2QNSoiI/deleteWebhook
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x037EE1F0>, 'Connect timed out. (connect timeout=5.0)')': /bot695750093:AAHKHhTZ5H3Zi_vUngfTlhHHUhhC2QNSoiI/deleteWebhook
ERROR:telegram.ext.updater:Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot695750093:AAHKHhTZ5H3Zi_vUngfTlhHHUhhC2QNSoiI/deleteWebhook (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x037EE1F0>, 'Connect timed out. (connect timeout=5.0)'))
WARNING:telegram.ext.updater:Failed bootstrap phase; try=1 max_retries=-1
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x037EE1F0>, 'Connect timed out. (connect timeout=5.0)')': /bot695750093:AAHKHhTZ5H3Zi_vUngfTlhHHUhhC2QNSoiI/deleteWebhook
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x037EE1F0>, 'Connect timed out. (connect timeout=5.0)')': /bot695750093:AAHKHhTZ5H3Zi_vUngfTlhHHUhhC2QNSoiI/deleteWebhook
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
